[package]
name = "delivery"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1"
chrono = "0.4"
hmac = "0.12.1"
sha2 = "0.10.2"
hex = "0.4.3"
reqwest = { version = "0.11.11", features = ["blocking", "json"] }


